In [2]:
import torch

In [3]:
torch.__version__

'2.8.0+cu126'

In [4]:
scalar = torch.Tensor(7)
scalar

tensor([-6.3698e+07,  4.5109e-41,  3.3293e-28,  0.0000e+00,  0.0000e+00,
         2.8904e-27,  4.6256e-26])

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [3]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.3070, 0.6809, 0.2683, 0.2687],
         [0.9144, 0.9044, 0.6170, 0.8600],
         [0.2689, 0.5489, 0.5827, 0.5302]]),
 torch.float32)

In [4]:
random_image = torch.rand(size=(224,224,3))
random_image.ndim, random_image.shape

(3, torch.Size([224, 224, 3]))

In [5]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [7]:
ones = torch.ones(size=(3,4))
ones,zeros.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [8]:
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
some_tensor = torch.rand(3,4)
some_tensor
print(f'Shape: {some_tensor.shape}')
print(f'Datatype: {some_tensor.dtype}')
print(f'Device: {some_tensor.device}')

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device: cpu
